Repository dromara/hmily, pull requests merged in 2020-08, with the labels that each got.

#137 Add .travis.yml
  .travis.yml
Labels: build

#135 mongo report
  hmily-demo/hmily-demo-springcloud/hmily-demo-springcloud-account/src/main/resources/application.yml
  hmily-demo/hmily-demo-springcloud/hmily-demo-springcloud-inventory/src/main/resources/application.yml
  hmily-demo/hmily-demo-springcloud/hmily-demo-springcloud-inventory/src/main/resources/applicationContext.xml
  hmily-demo/hmily-demo-springcloud/hmily-demo-springcloud-order/src/main/resources/applicationContext.xml
  hmily-demo/pom.xml
  hmily-repository/hmily-repository-mongodb/pom.xml
  hmily-repository/hmily-repository-mongodb/src/main/java/org/dromara/hmily/repository/mongodb/MongoEntityConvert.java
  hmily-repository/hmily-repository-mongodb/src/main/java/org/dromara/hmily/repository/mongodb/MongodbRepository.java
  hmily-repository/hmily-repository-mongodb/src/main/java/org/dromara/hmily/repository/mongodb/MongodbTemplateService.java
  hmily-repository/hmily-repository-mongodb/src/main/java/org/dromara/hmily/repository/mongodb/entity/MongoEntityAdapter.java
  hmily-repository/hmily-repository-mongodb/src/main/java/org/dromara/hmily/repository/mongodb/entity/ParticipantMongoEntity.java
  hmily-repository/hmily-repository-mongodb/src/main/java/org/dromara/hmily/repository/mongodb/entity/TransactionMongoEntity.java
  hmily-repository/hmily-repository-mongodb/src/main/java/org/dromara/hmily/repository/mongodb/entity/UndoMongoEntity.java
  pom.xml
Labels: good first issue

#136 Change the way of all of the four kinds of databases init ，& checkstyle pass, & add postgresql create database
  hmily-repository/hmily-repository-database/hmily-repository-database-manager/src/main/java/org/dromara/hmily/repository/database/manager/AbstractHmilyDatabase.java
  hmily-repository/hmily-repository-database/hmily-repository-database-mysql/src/main/java/org/dromara/hmily/repository/database/mysql/MysqlRepository.java
  hmily-repository/hmily-repository-database/hmily-repository-database-oracle/src/main/java/org/dromara/hmily/repository/database/oracle/OracleRepository.java
  hmily-repository/hmily-repository-database/hmily-repository-database-postgresql/src/main/java/org/dromara/hmily/repository/database/postgresql/PostgresqlRepository.java
  hmily-repository/hmily-repository-database/hmily-repository-database-postgresql/src/main/resources/postgresql/schema.sql
  hmily-repository/hmily-repository-database/hmily-repository-database-sqlserver/src/main/java/org/dromara/hmily/repository/database/sqlserver/SqlserverRepository.java
Labels: help wanted

#141 fix travis
  .travis.yml
  README.md
Labels: build

#142 fix cobertura
  README-EN.md
  README.md
  pom.xml
Labels: build

#155 repository-zookeeper 添加mock测试
  hmily-repository/hmily-repository-zookeeper/pom.xml
  hmily-repository/hmily-repository-zookeeper/src/main/java/org/dromara/hmily/repository/zookeeper/ZookeeperRepository.java
  hmily-repository/hmily-repository-zookeeper/src/test/java/org/dromara/hmily/repository/zookeeper/ZookeeperRepositoryTest.java
  hmily-repository/hmily-repository-zookeeper/src/test/java/org/dromara/hmily/repository/zookeeper/mock/ZookeeperMock.java
  pom.xml
Labels: good first issue, help wanted, spi
