Repository dromara/hmily, pull requests merged in 2020-11, with the labels that each got.

#238 refactor HmilyUndoInvocation => HmilyDataSnapshot
  hmily-repository/hmily-repository-database/hmily-repository-database-manager/src/main/java/org/dromara/hmily/repository/database/manager/AbstractHmilyDatabase.java
  hmily-repository/hmily-repository-database/hmily-repository-database-mysql/src/main/resources/mysql/schema.sql
  hmily-repository/hmily-repository-database/hmily-repository-database-oracle/src/main/resources/oracle/schema.sql
  hmily-repository/hmily-repository-database/hmily-repository-database-postgresql/src/main/resources/postgresql/schema.sql
  hmily-repository/hmily-repository-database/hmily-repository-database-sqlserver/src/main/resources/sqlserver/schema.sql
  hmily-repository/hmily-repository-mongodb/src/main/java/org/dromara/hmily/repository/mongodb/MongoEntityConvert.java
  hmily-repository/hmily-repository-mongodb/src/main/java/org/dromara/hmily/repository/mongodb/entity/UndoMongoEntity.java
  hmily-repository/hmily-repository-spi/src/main/java/org/dromara/hmily/repository/spi/entity/HmilyDataSnapshot.java
  hmily-repository/hmily-repository-spi/src/main/java/org/dromara/hmily/repository/spi/entity/HmilyParticipantUndo.java
  hmily-tac/hmily-tac-core/src/main/java/org/dromara/hmily/tac/core/context/HmilyUndoContext.java
  hmily-tac/hmily-tac-p6spy/src/main/java/org/dromara/hmily/tac/p6spy/executor/HmilyExecuteTemplate.java
  hmily-tac/hmily-tac-sqlcompute/src/main/java/org/dromara/hmily/tac/sqlcompute/HmilySQLComputeEngine.java
  hmily-tac/hmily-tac-sqlcompute/src/main/java/org/dromara/hmily/tac/sqlcompute/impl/AbstractHmilySQLComputeEngine.java
  hmily-tac/hmily-tac-sqlcompute/src/main/java/org/dromara/hmily/tac/sqlcompute/impl/HmilyDeleteSQLComputeEngine.java
  hmily-tac/hmily-tac-sqlcompute/src/main/java/org/dromara/hmily/tac/sqlcompute/impl/HmilyInsertSQLComputeEngine.java
  hmily-tac/hmily-tac-sqlcompute/src/main/java/org/dromara/hmily/tac/sqlcompute/impl/HmilyUpdateSQLComputeEngine.java
  hmily-tac/hmily-tac-sqlrevert/hmily-tac-sqlrevert-core/src/main/java/org/dromara/hmily/tac/sqlrevert/core/DefaultSQLRevertEngine.java
Labels: SQL revert

#241 Optimize repository module code.
  hmily-core/src/main/java/org/dromara/hmily/core/schedule/HmilyTransactionSelfRecoveryScheduled.java
  hmily-repository/hmily-repository-database/hmily-repository-database-manager/src/main/java/org/dromara/hmily/repository/database/manager/AbstractHmilyDatabase.java
  hmily-repository/hmily-repository-etcd/src/main/java/org/dromara/hmily/repository/etcd/EtcdRepository.java
  hmily-repository/hmily-repository-etcd/src/test/java/org/dromara/hmily/repository/etcd/EtcdRepositoryTest.java
  hmily-repository/hmily-repository-file/src/main/java/org/dromara/hmily/repository/file/FileRepository.java
  hmily-repository/hmily-repository-file/src/test/java/org/dromara/hmily/repository/file/FileRepositoryTest.java
  hmily-repository/hmily-repository-mongodb/src/main/java/org/dromara/hmily/repository/mongodb/MongodbRepository.java
  hmily-repository/hmily-repository-redis/src/main/java/org/dromara/hmily/repository/redis/RedisRepository.java
  hmily-repository/hmily-repository-spi/src/main/java/org/dromara/hmily/repository/spi/HmilyRepository.java
  hmily-repository/hmily-repository-zookeeper/src/main/java/org/dromara/hmily/repository/zookeeper/ZookeeperRepository.java
  hmily-repository/hmily-repository-zookeeper/src/test/java/org/dromara/hmily/repository/zookeeper/ZookeeperRepositoryTest.java
Labels: reafactor

#242 introduce metadata to SQLCompute engine
  hmily-tac/hmily-tac-p6spy/src/main/java/org/dromara/hmily/tac/p6spy/executor/HmilyExecuteTemplate.java
  hmily-tac/hmily-tac-p6spy/src/main/java/org/dromara/hmily/tac/p6spy/listener/HmilyJdbcEventListener.java
  hmily-tac/hmily-tac-sqlcompute/src/main/java/org/dromara/hmily/tac/sqlcompute/HmilySQLComputeEngine.java
  hmily-tac/hmily-tac-sqlcompute/src/main/java/org/dromara/hmily/tac/sqlcompute/impl/AbstractHmilySQLComputeEngine.java
  hmily-tac/hmily-tac-sqlcompute/src/main/java/org/dromara/hmily/tac/sqlcompute/impl/HmilyDeleteSQLComputeEngine.java
  hmily-tac/hmily-tac-sqlcompute/src/main/java/org/dromara/hmily/tac/sqlcompute/impl/HmilyInsertSQLComputeEngine.java
  hmily-tac/hmily-tac-sqlcompute/src/main/java/org/dromara/hmily/tac/sqlcompute/impl/HmilyUpdateSQLComputeEngine.java
Labels: SQL revert

#243 Optimize repository module code.
  hmily-repository/hmily-repository-etcd/src/main/java/org/dromara/hmily/repository/etcd/EtcdRepository.java
  hmily-repository/hmily-repository-file/src/main/java/org/dromara/hmily/repository/file/FileRepository.java
  hmily-repository/hmily-repository-spi/src/main/java/org/dromara/hmily/repository/spi/HmilyRepositoryNode.java
  hmily-repository/hmily-repository-zookeeper/src/main/java/org/dromara/hmily/repository/zookeeper/ZookeeperRepository.java
Labels: reafactor

#251 prometheus spell error
  hmily-metrics/hmily-metrics-facade/pom.xml
Labels: build

#256 Brpc demo 测试版
  hmily-demo/hmily-demo-brpc/hmily-demo-brpc-account/pom.xml
  hmily-demo/hmily-demo-brpc/hmily-demo-brpc-account/src/main/java/org/dromara/hmily/demo/brpc/account/config/HmilyTacDatasourceConfig.java
  hmily-demo/hmily-demo-brpc/hmily-demo-brpc-account/src/main/resources/application.yml
  hmily-demo/hmily-demo-brpc/hmily-demo-brpc-account/src/main/resources/hmily.yml
  hmily-demo/hmily-demo-brpc/hmily-demo-brpc-inventory/pom.xml
  hmily-demo/hmily-demo-brpc/hmily-demo-brpc-inventory/src/main/resources/application.yml
  hmily-demo/hmily-demo-brpc/hmily-demo-brpc-inventory/src/main/resources/applicationContext.xml
  hmily-demo/hmily-demo-brpc/hmily-demo-brpc-inventory/src/main/resources/hmily.yml
  hmily-demo/hmily-demo-brpc/hmily-demo-brpc-order/pom.xml
  hmily-demo/hmily-demo-brpc/hmily-demo-brpc-order/src/main/resources/application.yml
  hmily-demo/hmily-demo-brpc/hmily-demo-brpc-order/src/main/resources/hmily.yml
  hmily-demo/hmily-demo-brpc/pom.xml
  hmily-rpc/hmily-brpc/pom.xml
  hmily-rpc/hmily-brpc/src/main/java/org/dromara/hmily/brpc/field/BrpcRefererAnnotationField.java
  hmily-rpc/hmily-brpc/src/main/java/org/dromara/hmily/brpc/interceptor/BrpcHmilyTransactionInterceptor.java
  hmily-rpc/hmily-brpc/src/main/java/org/dromara/hmily/brpc/loadbalance/HmilyLoadBalanceUtils.java
  hmily-rpc/hmily-brpc/src/main/java/org/dromara/hmily/brpc/loadbalance/HmilyRobinStrategy.java
  hmily-rpc/hmily-brpc/src/main/java/org/dromara/hmily/brpc/parameter/BrpcParameterLoader.java
  hmily-spring-boot-starter/hmily-spring-boot-starter-brpc/pom.xml
Labels: brpc

#257 fix doc and sync doc between cn and en
  README.md
  README_cn.md
Labels: document
